title: 'Margot Nadot'
default_lang: fr
author:
  name: 'Margot Nadot'
  email: margot.nadot@gmail.com
taxonomies:
  - tag
  - technique
  - client
metadata:
  description: 'My Grav Site'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
